### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by StephenNorCalControls** [adam-nielsen/lz2treefile#1]
What specification did you use to create this application? I want to do something similar in Python but I can't find a spec document that describes how to decompose the file. Was this a reverse-engineering job or did you find a reference somewhere?

**Comment by adam-nielsen** [comment]
It was a reverse engineering job, there was no doco available and the vendor using this format wasn't willing to provide any!

**Comment by StephenNorCalControls** [comment]
Ah ok, thanks for the info!
