### ISSUE TITLE
Slight Decompression Errors

### ISSUE THREAD

**Issue by robinsheehy** [adam-nielsen/lz2treefile#3]
Hello,

Thanks so much for providing this code it is very useful to me.

I am seeing some unusual errors in my output that I have been unable to understand or debug.

As I am on windows I have changed the input read from '/dev/stdin' to the file I am testing with, but otherwise the code is unchanged.

I have replicated the issue in an almost blank CD3 file included in the attached ZIP file. The ZIP file also includes and equivalent CD2 file and the output of the decompression of the CD3 file.

[CSMSTRSX-DIO.zip](https://github.com/adam-nielsen/lz2treefile/files/15145539/CSMSTRSX-DIO.zip)

Basically, at line 1882 the output is a line of many P’s This looks like

            Symbol1 {
             Left            = 530
             Top             = 119
             Width           = 20
             Height          = 10
             Type            = 3
             NumInputs       = 1
             NumOutputs      = 0
             PinSpace        = 0
             PinOffset       = 6
             BMPOffsetX      = 0
             Prop            = 0
             Prop            = 0
             PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPinWire         = 0
             PinWire         = 0
             WireEnd         = 0
             WireEnd         = 0
             }

I can’t be 100% certain what the output should look like but in a CD2 file of the same setup (CD2 files are not compressed) the same section found at line 483 is as follows.

        Symbol1 {
         Left            = 530
         Top             = 119
         Width           = 20
         Height          = 10
         Type            = 3
         NumInputs       = 1
         NumOutputs      = 0
         PinSpace        = 0
         PinOffset       = 6
         BMPOffsetX      = 0
         Prop            = 0
         Prop            = 0
         Prop            = 0
         Prop            = 0
         Prop            = 0
         PinWire         = 0
         PinWire         = 0
         WireEnd         = 0
         WireEnd         = 0
         }

I think that looking at the error and expected output that the issue is in the block that repeats characters, I think that sometimes the logic for this is slightly different and repeats blocks of characters, rather than just the last character in the chunk. I am not sure but I think this maybe when lbDist is > 0 when repeat is non zero. But that is just me guessing.

If you could assist that would be awesome.

**Comment by adam-nielsen** [comment]
Thanks for the info and sample files.  It looks like you're right, and I hardcoded the repeat as a single character when actually it is `lbDist` number of characters.  Apparently none of my files were complex enough to hit this condition!

I have pushed a fix which appears to correctly decode your sample file so hopefully that works for you too.

**Comment by robinsheehy** [comment]
Thanks so much, that is working for me!

Did you ever look at implementing the compression side, that is my next step and wondered if you had any insight.

**Comment by adam-nielsen** [comment]
I never got far enough for that, but my initial idea was to just write an escape byte followed by the maximum length of escape data, and just repeat it for the length of the file.  It wouldn't compress at all but it would at least be readable by any software expecting a compressed file, and should be pretty quick to implement.

It's been a while but it looks like an `0x1F` byte would get treated as an escape, signalling that the following 32 bytes should be passed through unchanged.  So it seems passing the first 22 bytes through as-is will cater for the initial state, then an `0x1F` byte should be inserted followed by the next 32 bytes, repeated until less than 32 bytes remain.  Then a final escape byte should be inserted (of value `length - 1`) followed by the remaining bytes.

I am probably missing something so don't take that too precisely, but hopefully it at least gives you something to start with.
